import {StyleSheet} from 'react-native';
import {colors} from '../constants/theme';

const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: colors.background},
  safeAreaDark: {backgroundColor: colors.darkBackground},
  topBar: {height: 68, paddingHorizontal: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  brandMark: {width: 42, height: 42, borderRadius: 13, overflow: 'hidden', backgroundColor: colors.ink},
  brandMarkDark: {borderWidth: 1, borderColor: colors.darkBorder},
  brandMarkImage: {width: '100%', height: '100%'},
  skipButton: {minWidth: 64, height: 38, borderRadius: 13, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paper},
  skipButtonDark: {backgroundColor: colors.darkSurface, borderColor: colors.darkBorder},
  skipText: {fontSize: 13, color: colors.ink, fontWeight: '800'},
  scrollContent: {flexGrow: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24, paddingVertical: 16},
  contentWidth: {width: '100%', maxWidth: 560, alignItems: 'center'},
  artCard: {width: '100%', maxWidth: 360, height: 294, alignItems: 'center', justifyContent: 'center', borderRadius: 30, backgroundColor: '#F2ECE4', overflow: 'hidden'},
  artCardDark: {backgroundColor: colors.darkSurface},
  artHalo: {position: 'absolute', width: 150, height: 150, borderRadius: 75, right: 23, top: 24, overflow: 'hidden'},
  artPageBack: {position: 'absolute', width: 188, height: 226, borderRadius: 8, backgroundColor: '#E8CFC4', transform: [{rotate: '7deg'}]},
  artPage: {width: 188, height: 226, borderRadius: 8, padding: 22, justifyContent: 'space-between', backgroundColor: colors.ink, transform: [{rotate: '-2deg'}], shadowColor: colors.shadow, shadowOpacity: 0.24, shadowRadius: 14, shadowOffset: {width: 0, height: 9}, elevation: 7},
  artPageDark: {borderWidth: 1, borderColor: colors.darkBorder},
  artWordmark: {fontSize: 10, letterSpacing: 2.2, color: colors.focus, fontWeight: '900'},
  artRule: {position: 'absolute', left: 22, top: 65, width: 34, height: 3, backgroundColor: colors.accent},
  artPageNumber: {fontSize: 11, letterSpacing: 1.5, color: colors.readerSub, fontWeight: '800'},
  copyBlock: {width: '100%', maxWidth: 440, alignItems: 'center', marginTop: 28},
  eyebrow: {fontSize: 10, letterSpacing: 2.1, color: colors.accent, fontWeight: '900'},
  title: {fontFamily: 'serif', fontSize: 36, lineHeight: 43, color: colors.ink, textAlign: 'center', fontWeight: '700', marginTop: 9},
  copy: {fontSize: 14, lineHeight: 21, color: colors.muted, textAlign: 'center', marginTop: 11},
  note: {maxWidth: 390, flexDirection: 'row', alignItems: 'center', borderRadius: 13, backgroundColor: colors.paper, paddingHorizontal: 13, paddingVertical: 10, marginTop: 17},
  noteDark: {backgroundColor: colors.darkSurfaceRaised},
  noteDot: {width: 7, height: 7, borderRadius: 4, backgroundColor: colors.focus, marginRight: 9},
  noteText: {flexShrink: 1, fontSize: 11, lineHeight: 16, color: colors.muted},
  textDark: {color: colors.darkInk},
  mutedDark: {color: colors.darkMuted},
  footer: {paddingHorizontal: 24, paddingTop: 10, paddingBottom: 16, alignItems: 'center'},
  dots: {height: 14, flexDirection: 'row', alignItems: 'center', gap: 7},
  dot: {width: 7, height: 7, borderRadius: 4, backgroundColor: colors.border},
  dotDark: {backgroundColor: colors.darkBorder},
  dotActive: {width: 24, backgroundColor: colors.focus},
  actions: {width: '100%', maxWidth: 560, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12},
  backButton: {width: 48, height: 48, borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.paper, alignItems: 'center', justifyContent: 'center'},
  backButtonDark: {backgroundColor: colors.darkSurface, borderColor: colors.darkBorder},
  hiddenButton: {opacity: 0},
  nextButton: {minWidth: 126, height: 50, paddingHorizontal: 18, borderRadius: 16, overflow: 'hidden', flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.ink},
  nextButtonText: {fontSize: 14, color: colors.ink, fontWeight: '900'},
  pressed: {opacity: 0.72, transform: [{scale: 0.985}]},
  disabled: {opacity: 0.55},
});

export default styles;
