import { StyleSheet } from 'react-native';
import { colors } from '../constants/theme';

const LISTENING_YELLOW = '#F2C94C';
const INK = '#171614';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FBFAF7' },
  safeAreaDark: { backgroundColor: '#12110F' },
  header: {
    minHeight: 62,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerLandscape: { minHeight: 50, paddingHorizontal: 14 },
  headerButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.09,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  headerButtonText: {
    fontSize: 32,
    lineHeight: 34,
    color: INK,
    fontWeight: '300',
  },
  headerButtonDark: { backgroundColor: '#25221F', shadowOpacity: 0.35 },
  headerButtonTextDark: { color: '#F8F3EC' },
  headerCopy: { flex: 1, alignItems: 'center', paddingHorizontal: 8 },
  eyebrow: {
    fontSize: 9,
    letterSpacing: 1.8,
    color: colors.accentDark,
    fontWeight: '900',
  },
  headerTitle: {
    fontFamily: 'serif',
    fontSize: 20,
    color: INK,
    marginTop: 2,
  },
  pageBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    overflow: 'hidden',
    backgroundColor: INK,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageBadgeText: { fontSize: 12, color: '#FFFFFF', fontWeight: '800' },
  pageBadgeDark: { backgroundColor: 'transparent' },
  pageBadgeTextDark: { color: INK },
  content: {
    paddingHorizontal: 26,
    paddingTop: 18,
    paddingBottom: 36,
    alignItems: 'center',
  },
  contentLandscape: {
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingTop: 6,
    paddingBottom: 10,
    justifyContent: 'center',
  },
  listeningBody: { width: '100%', alignItems: 'center' },
  listeningBodyLandscape: {
    maxWidth: 980,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 44,
  },
  visualColumn: { alignItems: 'center' },
  visualColumnLandscape: { width: 230, flexShrink: 0 },
  playbackColumn: { width: '100%', alignItems: 'center' },
  playbackColumnLandscape: { flex: 1, maxWidth: 620 },
  coverScene: {
    width: 210,
    height: 240,
    alignItems: 'center',
    justifyContent: 'center',
  },
  coverSceneLandscape: { width: 170, height: 178 },
  accentOrb: {
    position: 'absolute',
    width: 62,
    height: 62,
    borderRadius: 31,
    overflow: 'hidden',
    right: 0,
    top: 5,
    borderWidth: 1,
    borderColor: INK,
  },
  coverShadow: {
    position: 'absolute',
    width: 142,
    height: 198,
    backgroundColor: 'rgba(215,109,69,0.17)',
    transform: [{ rotate: '6deg' }],
  },
  coverShadowLandscape: { width: 108, height: 150 },
  cover: {
    width: 142,
    height: 198,
    backgroundColor: INK,
    paddingHorizontal: 18,
    paddingVertical: 17,
    justifyContent: 'space-between',
    shadowColor: '#000000',
    shadowOpacity: 0.24,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  coverLandscape: {
    width: 108,
    height: 150,
    paddingHorizontal: 13,
    paddingVertical: 12,
  },
  coverMark: {
    fontSize: 8,
    letterSpacing: 1.8,
    color: LISTENING_YELLOW,
    fontWeight: '900',
  },
  coverRule: { width: 28, height: 2, backgroundColor: colors.accent },
  coverTitle: {
    fontFamily: 'serif',
    fontSize: 18,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  coverPage: {
    fontSize: 8,
    letterSpacing: 1.4,
    color: '#BEBBB5',
    fontWeight: '800',
  },
  coverShadowDark: { backgroundColor: 'rgba(242,201,76,0.14)' },
  coverDark: { borderWidth: 1, borderColor: '#4B4741' },
  bookTitle: {
    fontFamily: 'serif',
    textAlign: 'center',
    fontSize: 21,
    lineHeight: 27,
    color: INK,
    fontWeight: '700',
  },
  bookTitleLandscape: { fontSize: 17, lineHeight: 21 },
  narratorMeta: {
    fontSize: 11,
    color: '#817C74',
    marginTop: 5,
    fontWeight: '700',
  },
  textDark: { color: '#F8F3EC' },
  mutedDark: { color: '#AFA79D' },
  transcript: {
    width: '100%',
    minHeight: 158,
    justifyContent: 'center',
    marginTop: 24,
  },
  transcriptLandscape: { minHeight: 112, marginTop: 0 },
  contextText: {
    fontSize: 15,
    lineHeight: 23,
    color: 'rgba(23,22,20,0.18)',
    textAlign: 'center',
  },
  contextTextDark: { color: 'rgba(248,243,236,0.23)' },
  activeTextWrap: {
    marginVertical: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  activeTextAccent: {
    position: 'absolute',
    left: 0,
    top: 10,
    bottom: 10,
    width: 3,
    backgroundColor: LISTENING_YELLOW,
  },
  activeText: {
    fontSize: 17,
    lineHeight: 26,
    color: INK,
    textAlign: 'center',
    fontWeight: '600',
  },
  chunkRow: { width: '100%', alignItems: 'center', marginTop: 8 },
  chunkText: {
    fontSize: 10,
    color: INK,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  controls: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 38,
    marginTop: 25,
  },
  controlsLandscape: { marginTop: 12 },
  skipButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  skipText: { fontSize: 24, color: INK, fontWeight: '800' },
  playButton: {
    width: 68,
    height: 68,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: INK,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playButtonDark: { backgroundColor: 'transparent' },
  playButtonBusy: { backgroundColor: 'transparent' },
  playText: { fontSize: 23, color: '#FFFFFF', fontWeight: '900' },
  playTextDark: { color: INK },
  disabled: { opacity: 0.2 },
  stopButton: { marginTop: 22, paddingHorizontal: 18, paddingVertical: 10 },
  stopText: {
    fontSize: 10,
    letterSpacing: 1.2,
    color: '#8A837A',
    fontWeight: '900',
  },
});

export default styles;
