import {StyleSheet} from 'react-native';
import {colors} from '../constants/theme';

const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: colors.background},
  centered: {flex: 1, alignItems: 'center', justifyContent: 'center'},
  libraryHeader: {paddingHorizontal: 22, paddingTop: 22, paddingBottom: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  eyebrow: {fontSize: 11, letterSpacing: 2.1, color: colors.accentDark, fontWeight: '700'},
  title: {fontSize: 30, color: colors.ink, fontFamily: 'serif', fontWeight: '700', marginTop: 4},
  importButton: {height: 44, minWidth: 82, borderRadius: 22, paddingHorizontal: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.accent},
  importButtonText: {color: colors.white, fontSize: 14, fontWeight: '800', letterSpacing: 0.5},
  pressed: {opacity: 0.78, transform: [{scale: 0.98}]},
  emptyState: {flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 35, paddingBottom: 60},
  emptyBook: {width: 132, height: 174, borderRadius: 8, backgroundColor: colors.coverOchre, transform: [{rotate: '-4deg'}], alignItems: 'center', justifyContent: 'center', shadowColor: colors.shadow, shadowOpacity: 0.22, shadowRadius: 14, shadowOffset: {width: 0, height: 10}, elevation: 7},
  emptyBookSpine: {position: 'absolute', left: 12, top: 0, bottom: 0, width: 2, backgroundColor: 'rgba(255,255,255,0.24)'},
  emptyBookGlyph: {fontFamily: 'serif', fontSize: 42, color: colors.glyphText, fontWeight: '700'},
  emptyTitle: {fontFamily: 'serif', fontSize: 25, fontWeight: '700', color: colors.ink, marginTop: 30},
  emptyCopy: {fontSize: 15, lineHeight: 23, color: colors.muted, textAlign: 'center', marginTop: 10, maxWidth: 330},
  primaryButton: {marginTop: 24, paddingHorizontal: 24, height: 48, borderRadius: 24, backgroundColor: colors.ink, justifyContent: 'center'},
  primaryButtonText: {fontSize: 15, fontWeight: '700', color: colors.white},
  shelf: {paddingHorizontal: 20, paddingBottom: 30},
  savedWordsButton: {marginHorizontal: 20, marginBottom: 16, backgroundColor: colors.paper, borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 12, flexDirection: 'row', alignItems: 'center', shadowColor: colors.shadow, shadowOpacity: 0.06, shadowRadius: 8, shadowOffset: {width: 0, height: 4}, elevation: 2},
  savedWordsGlyph: {width: 44, height: 44, borderRadius: 10, backgroundColor: colors.coverOchre, alignItems: 'center', justifyContent: 'center'},
  savedWordsGlyphText: {fontFamily: 'serif', fontSize: 18, color: colors.glyphText, fontWeight: '700'},
  savedWordsMeta: {flex: 1, marginLeft: 12},
  savedWordsTitle: {fontSize: 15, fontWeight: '700', color: colors.ink},
  savedWordsSub: {fontSize: 12, color: colors.muted, marginTop: 2},
  savedWordsArrow: {fontSize: 26, lineHeight: 28, color: colors.muted, fontWeight: '300'},
  sectionLabel: {fontSize: 11, letterSpacing: 1.8, fontWeight: '700', color: colors.muted, marginBottom: 12},
  bookCard: {backgroundColor: colors.paper, borderRadius: 18, marginBottom: 16, padding: 14, flexDirection: 'row', borderWidth: 1, borderColor: colors.border, shadowColor: colors.shadow, shadowOpacity: 0.07, shadowRadius: 9, shadowOffset: {width: 0, height: 5}, elevation: 2},
  bookCover: {width: 94, height: 130, borderRadius: 7, padding: 12, justifyContent: 'space-between', shadowColor: colors.shadow, shadowOpacity: 0.2, shadowRadius: 5, shadowOffset: {width: 2, height: 4}, elevation: 3},
  coverTerracotta: {backgroundColor: colors.coverTerracotta},
  coverOlive: {backgroundColor: colors.coverOlive},
  coverRule: {height: 1, width: 24, backgroundColor: colors.coverRule},
  coverTitle: {fontFamily: 'serif', fontSize: 13, lineHeight: 16, color: colors.coverText, fontWeight: '700'},
  coverMark: {fontSize: 7, letterSpacing: 1.2, color: colors.coverMark},
  bookMeta: {flex: 1, marginLeft: 17, paddingVertical: 5},
  bookTitle: {fontFamily: 'serif', fontSize: 19, lineHeight: 24, fontWeight: '700', color: colors.ink},
  bookDetails: {fontSize: 12, color: colors.muted, marginTop: 7},
  progressTrack: {height: 4, backgroundColor: colors.track, borderRadius: 2, marginTop: 13, overflow: 'hidden'},
  progressFill: {height: 4, backgroundColor: colors.accent, borderRadius: 2},
  continueText: {fontSize: 12, color: colors.accentDark, fontWeight: '700', marginTop: 12},
  dictBadge: {marginTop: 10, alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', backgroundColor: colors.badgeBg, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 3},
  dictBadgeText: {fontSize: 11, fontWeight: '700', color: colors.badgeText},
});

export default styles;