import {StyleSheet} from 'react-native';
import {colors} from '../constants/theme';

const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: colors.background},
  safeAreaDark: {backgroundColor: colors.darkBackground},
  textDark: {color: colors.darkInk},
  mutedDark: {color: colors.darkMuted},
  cardDark: {backgroundColor: colors.darkSurface, borderColor: colors.darkBorder},
  centered: {flex: 1, alignItems: 'center', justifyContent: 'center'},
  brandBar: {minHeight: 64, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center'},
  brandMark: {width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.ink, transform: [{rotate: '-4deg'}]},
  brandMarkText: {fontFamily: 'serif', fontSize: 20, color: colors.focus, fontWeight: '800'},
  brandCopy: {flex: 1, marginLeft: 11},
  brandName: {fontFamily: 'serif', fontSize: 18, color: colors.ink, fontWeight: '800'},
  brandTagline: {fontSize: 10, color: colors.muted, marginTop: -1},
  avatarButton: {width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.focus, borderWidth: 1, borderColor: colors.ink},
  avatarText: {fontFamily: 'serif', fontSize: 17, color: colors.ink, fontWeight: '800'},
  content: {paddingHorizontal: 20, paddingTop: 17, paddingBottom: 112},
  titleRow: {flexDirection: 'row', alignItems: 'center', marginBottom: 28},
  titleCopy: {flex: 1},
  eyebrow: {fontSize: 10, letterSpacing: 2, color: colors.accent, fontWeight: '900'},
  title: {fontFamily: 'serif', fontSize: 36, lineHeight: 42, color: colors.ink, fontWeight: '700'},
  bookCount: {fontSize: 13, color: colors.muted, marginTop: 2},
  importButton: {height: 44, minWidth: 82, borderRadius: 15, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.ink},
  importButtonText: {color: colors.focus, fontSize: 14, fontWeight: '900'},
  importButtonDark: {backgroundColor: colors.focus},
  importButtonTextDark: {color: colors.ink},
  disabled: {opacity: 0.55},
  pressed: {opacity: 0.78, transform: [{scale: 0.985}]},
  sectionLabel: {fontSize: 10, letterSpacing: 1.8, fontWeight: '800', color: colors.muted, marginBottom: 10},
  currentCard: {backgroundColor: colors.paper, borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 15, flexDirection: 'row', shadowColor: colors.shadow, shadowOpacity: 0.1, shadowRadius: 16, shadowOffset: {width: 0, height: 8}, elevation: 4},
  bookCover: {width: 100, height: 142, borderRadius: 8, padding: 12, justifyContent: 'space-between', shadowColor: colors.shadow, shadowOpacity: 0.2, shadowRadius: 5, shadowOffset: {width: 2, height: 4}, elevation: 3},
  bookCoverCompact: {width: 62, height: 88, padding: 8, borderRadius: 6},
  coverTerracotta: {backgroundColor: colors.coverTerracotta},
  coverOlive: {backgroundColor: colors.coverOlive},
  coverRule: {height: 1, width: 25, backgroundColor: colors.coverRule},
  coverTitle: {fontFamily: 'serif', fontSize: 13, lineHeight: 17, color: colors.coverText, fontWeight: '700'},
  coverTitleCompact: {fontSize: 9, lineHeight: 11},
  coverMark: {fontSize: 7, letterSpacing: 1.2, color: colors.coverMark},
  currentMeta: {flex: 1, marginLeft: 18, paddingVertical: 5, justifyContent: 'center'},
  currentTitle: {fontFamily: 'serif', fontSize: 21, lineHeight: 26, fontWeight: '700', color: colors.ink},
  pageDetails: {fontSize: 12, color: colors.muted, marginTop: 7},
  progressTrack: {height: 4, backgroundColor: colors.track, borderRadius: 2, marginTop: 13, overflow: 'hidden'},
  progressTrackDark: {backgroundColor: colors.trackDark},
  progressFill: {height: 4, backgroundColor: colors.focus, borderRadius: 2},
  continueText: {fontSize: 12, color: colors.accent, fontWeight: '900', marginTop: 12},
  dictBadge: {marginTop: 9, alignSelf: 'flex-start', backgroundColor: colors.badgeBg, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 3},
  dictBadgeText: {fontSize: 10, fontWeight: '800', color: colors.badgeText},
  recentLabel: {marginTop: 27},
  bookCard: {backgroundColor: colors.paper, borderRadius: 17, marginBottom: 12, padding: 12, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.border},
  bookMeta: {flex: 1, marginLeft: 15},
  bookTitle: {fontFamily: 'serif', fontSize: 17, lineHeight: 22, fontWeight: '700', color: colors.ink},
  cardArrow: {fontSize: 28, color: colors.accent, marginLeft: 10, marginRight: 3},
  storageSummary: {alignItems: 'center', paddingTop: 15},
  storageText: {fontSize: 11, color: colors.muted},
  emptyState: {alignItems: 'center', paddingHorizontal: 20, paddingTop: 38, paddingBottom: 55},
  emptyBook: {width: 120, height: 156, borderRadius: 8, backgroundColor: colors.coverOchre, transform: [{rotate: '-4deg'}], alignItems: 'center', justifyContent: 'center', shadowColor: colors.shadow, shadowOpacity: 0.2, shadowRadius: 12, shadowOffset: {width: 0, height: 8}, elevation: 6},
  emptyBookSpine: {position: 'absolute', left: 12, top: 0, bottom: 0, width: 2, backgroundColor: 'rgba(255,255,255,0.24)'},
  emptyBookGlyph: {fontFamily: 'serif', fontSize: 38, color: colors.glyphText, fontWeight: '700'},
  emptyTitle: {fontFamily: 'serif', fontSize: 24, fontWeight: '700', color: colors.ink, marginTop: 26},
  emptyCopy: {fontSize: 14, lineHeight: 22, color: colors.muted, textAlign: 'center', marginTop: 9, maxWidth: 330},
  emptyButton: {marginTop: 22, paddingHorizontal: 23, height: 46, borderRadius: 15, backgroundColor: colors.ink, justifyContent: 'center'},
  emptyButtonText: {fontSize: 14, fontWeight: '800', color: colors.focus},
  emptyButtonDark: {backgroundColor: colors.focus},
  emptyButtonTextDark: {color: colors.ink},
});

export default styles;
