import { StyleSheet } from 'react-native';
import { colors, fonts } from '../constants/theme';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  safeAreaDark: { backgroundColor: colors.darkBackground },
  header: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 8 },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 2,
    color: colors.accent,
    fontWeight: '900',
  },
  headerTitle: {
    fontFamily: 'serif',
    fontSize: 40,
    lineHeight: 46,
    color: colors.ink,
    fontWeight: '700',
  },
  content: {
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 112,
  },
  avatar: {
    width: 94,
    height: 94,
    borderRadius: 30,
    backgroundColor: colors.ink,
    borderWidth: 2,
    borderColor: colors.focus,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-3deg' }],
    shadowColor: colors.shadow,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  avatarIcon: { width: 78, height: 78, resizeMode: 'contain' },
  name: {
    fontFamily: fonts.display,
    fontSize: 28,
    lineHeight: 34,
    color: colors.ink,
    marginTop: 20,
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 21,
    color: colors.muted,
    textAlign: 'center',
    maxWidth: 310,
    marginTop: 8,
  },
  statsCard: {
    width: '100%',
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    flexDirection: 'row',
    marginTop: 30,
    paddingVertical: 20,
    shadowColor: colors.shadow,
    shadowOpacity: 0.07,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
  },
  cardDark: {
    backgroundColor: colors.darkSurface,
    borderColor: colors.darkBorder,
  },
  stat: { flex: 1, alignItems: 'center' },
  statValue: { fontFamily: fonts.display, fontSize: 21, color: colors.ink },
  statLabel: {
    fontSize: 10,
    letterSpacing: 1.5,
    color: colors.muted,
    fontWeight: '800',
    marginTop: 5,
  },
  divider: { width: 1, backgroundColor: colors.border },
  dividerDark: { backgroundColor: colors.darkBorder },
  sectionHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginTop: 27,
    marginBottom: 10,
  },
  sectionTitle: {
    fontFamily: 'serif',
    fontSize: 21,
    color: colors.ink,
    fontWeight: '700',
  },
  sectionCount: { fontSize: 11, color: colors.muted },
  shelfCard: {
    width: '100%',
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    overflow: 'hidden',
  },
  shelfRow: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  shelfRowBorder: { borderBottomWidth: 1, borderBottomColor: colors.border },
  shelfRowBorderDark: { borderBottomColor: colors.darkBorder },
  shelfBookMark: {
    width: 42,
    height: 56,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.ink,
  },
  shelfMeta: { flex: 1, marginLeft: 13 },
  shelfTitle: {
    fontFamily: 'serif',
    fontSize: 16,
    lineHeight: 20,
    color: colors.ink,
    fontWeight: '700',
  },
  shelfStatus: { fontSize: 11, color: colors.muted, marginTop: 4 },
  removeButton: {
    width: 40,
    height: 40,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  removeButtonDark: {
    backgroundColor: colors.darkSurfaceRaised,
    borderColor: colors.darkBorder,
  },
  removeButtonPressed: { opacity: 0.65 },
  removeButtonDisabled: { opacity: 0.5 },
  emptyShelf: {
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 24,
  },
  emptyShelfTitle: { fontSize: 15, color: colors.ink, fontWeight: '800' },
  emptyShelfCopy: { fontSize: 12, color: colors.muted, marginTop: 5 },
  sectionDivider: {
    width: '100%',
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 22,
  },
  sectionDividerDark: { backgroundColor: colors.darkBorder },
  notice: {
    width: '100%',
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 18,
  },
  noticeTitle: { fontSize: 16, color: colors.ink, fontWeight: '800' },
  noticeCopy: {
    fontSize: 13,
    lineHeight: 20,
    color: colors.muted,
    marginTop: 7,
  },
  textDark: { color: colors.darkInk },
  mutedDark: { color: colors.darkMuted },
  versionNote: { fontSize: 10, color: colors.muted, marginTop: 24 },
});

export default styles;
