import { StyleSheet } from 'react-native';
import { colors } from '../constants/theme';

const styles = StyleSheet.create({
  readerSafeArea: { flex: 1, backgroundColor: colors.readerBg },
  reader: { flex: 1, backgroundColor: colors.readerBg },
  readerTopBar: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    zIndex: 5,
    backgroundColor: colors.readerBg,
  },
  iconButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonText: {
    fontSize: 35,
    lineHeight: 38,
    color: colors.readerInk,
    fontWeight: '300',
  },
  readerTitle: {
    flex: 1,
    textAlign: 'left',
    color: colors.readerInk,
    fontSize: 19,
    fontWeight: '700',
    paddingHorizontal: 8,
  },
  analyzeButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 19,
    backgroundColor: colors.analyzeBg,
  },
  analyzeButtonActive: { backgroundColor: colors.focus },
  captureGlyph: { width: 20, height: 20 },
  captureCorner: {
    position: 'absolute',
    width: 7,
    height: 7,
    borderColor: colors.readerInk,
  },
  captureCornerTopLeft: {
    left: 0,
    top: 0,
    borderLeftWidth: 2,
    borderTopWidth: 2,
  },
  captureCornerTopRight: {
    right: 0,
    top: 0,
    borderRightWidth: 2,
    borderTopWidth: 2,
  },
  captureCornerBottomLeft: {
    left: 0,
    bottom: 0,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
  },
  captureCornerBottomRight: {
    right: 0,
    bottom: 0,
    borderRightWidth: 2,
    borderBottomWidth: 2,
  },
  readerStage: { flex: 1, backgroundColor: '#CFCFD1', overflow: 'hidden' },
  readerStageDark: { backgroundColor: '#505050' },
  pager: { flex: 1, width: '100%', backgroundColor: '#CFCFD1' },
  pagerDark: { backgroundColor: '#505050' },
  pageSlot: { alignItems: 'center', justifyContent: 'flex-start' },
  pageFrame: { backgroundColor: '#CFCFD1', overflow: 'hidden' },
  pageFrameDark: { backgroundColor: '#505050' },
  pdfRenderedPage: { width: '100%', position: 'relative' },
  pdfPage: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: colors.white,
  },
  hidden: { opacity: 0 },
  pageButton: {
    flex: 1,
    height: 54,
    borderRadius: 16,
    marginHorizontal: 2,
    backgroundColor: colors.focus,
    alignItems: 'center',
    justifyContent: 'center',
  },
  disabledButton: { opacity: 0.25 },
  pageCounter: {
    flex: 1.35,
    height: 54,
    marginHorizontal: 2,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageCounterText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  pageCounterTextDark: { color: colors.darkInk },
  readerProgressTrack: {
    height: 3,
    width: '72%',
    backgroundColor: 'rgba(131, 125, 112, 0.5)',
    borderRadius: 2,
    overflow: 'hidden',
    marginTop: 7,
  },
  readerProgressFill: {
    height: 3,
    backgroundColor: colors.focus,
    borderRadius: 2,
  },
  narrationButton: {
    width: 38,
    height: 38,
    marginRight: 6,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.readerButtonBg,
  },

  narrationButtonActive: {
    backgroundColor: colors.focus,
  },

  narrationButtonText: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: '800',
  },

  immersiveButton: {
    width: 36,
    height: 36,
    marginRight: 6,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.focus,
  },

  immersiveButtonText: {
    color: colors.ink,
    fontSize: 19,
    fontWeight: '900',
  },
});

export default styles;
