import {StyleSheet} from 'react-native';
import {colors} from '../constants/theme';

const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: colors.background},
  safeAreaDark: {backgroundColor: '#171614'},
  textDark: {color: '#F7F0E6'},
  mutedDark: {color: '#BDB4A8'},
  cardDark: {backgroundColor: '#24211E', borderColor: '#3B3732'},
  header: {paddingHorizontal: 20, paddingTop: 20, paddingBottom: 14, flexDirection: 'row', alignItems: 'center'},
  headerCopy: {flex: 1},
  eyebrow: {fontSize: 10, letterSpacing: 2, color: colors.accentDark, fontWeight: '800'},
  title: {fontSize: 34, lineHeight: 40, color: colors.ink, fontFamily: 'serif', fontWeight: '700'},
  subtitle: {fontSize: 12, color: colors.muted, marginTop: 2},
  clearButton: {height: 36, paddingHorizontal: 14, borderRadius: 18, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center'},
  clearButtonText: {fontSize: 12, fontWeight: '800', color: colors.accentDark},
  disabled: {opacity: 0.35},
  searchBox: {height: 46, marginHorizontal: 20, marginBottom: 16, paddingHorizontal: 14, borderRadius: 15, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.border},
  searchBoxDark: {backgroundColor: '#24211E', borderColor: '#3B3732'},
  searchGlyph: {fontFamily: 'serif', fontSize: 13, color: colors.accentDark, fontWeight: '800', marginRight: 10},
  searchInput: {flex: 1, color: colors.ink, fontSize: 14, paddingVertical: 0},
  searchClear: {fontSize: 22, lineHeight: 24, color: colors.muted, paddingLeft: 10},
  centered: {flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 36},
  emptyGlyph: {width: 70, height: 70, borderRadius: 22, backgroundColor: colors.coverOlive, alignItems: 'center', justifyContent: 'center', marginBottom: 20},
  emptyGlyphText: {fontFamily: 'serif', fontSize: 25, color: colors.white, fontWeight: '700'},
  emptyTitle: {fontFamily: 'serif', fontSize: 22, fontWeight: '700', color: colors.ink, textAlign: 'center'},
  emptyCopy: {fontSize: 14, lineHeight: 22, color: colors.muted, textAlign: 'center', marginTop: 10, maxWidth: 330},
  list: {paddingHorizontal: 20, paddingBottom: 22},
  card: {backgroundColor: colors.paper, borderRadius: 17, borderWidth: 1, borderColor: colors.border, padding: 16, marginBottom: 11},
  cardHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  cardWord: {fontSize: 21, fontFamily: 'serif', fontWeight: '700', color: colors.ink},
  cardPos: {backgroundColor: '#F0D9CF', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, color: colors.accentDark, fontSize: 9, fontWeight: '800', overflow: 'hidden'},
  cardPosMuted: {fontSize: 14, color: colors.muted},
  cardNotFound: {marginTop: 8, fontSize: 13, color: colors.muted},
  previewRow: {flexDirection: 'row', alignItems: 'center'},
  cardPreview: {flex: 1, marginTop: 8, fontSize: 13, lineHeight: 19, color: colors.muted},
  expandArrow: {fontSize: 25, color: colors.accentDark, marginLeft: 10},
  cardDetail: {marginTop: 13, paddingTop: 11, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border},
  entry: {marginBottom: 11},
  entryPos: {fontSize: 9, letterSpacing: 1.2, color: colors.accentDark, fontWeight: '800', marginBottom: 5},
  definition: {fontSize: 14, lineHeight: 21, color: colors.ink},
  example: {marginTop: 7, fontSize: 13, lineHeight: 19, color: colors.muted, fontStyle: 'italic'},
  collapseHint: {fontSize: 10, color: colors.accentDark, fontWeight: '700', textAlign: 'right'},
  attribution: {fontSize: 10, color: colors.muted, textAlign: 'center', marginTop: 8},
});

export default styles;
