import {StyleSheet} from 'react-native';
import {colors} from '../constants/theme';

const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: colors.background},
  safeAreaDark: {backgroundColor: colors.darkBackground},
  textDark: {color: colors.darkInk},
  mutedDark: {color: colors.darkMuted},
  cardDark: {backgroundColor: colors.darkSurface, borderColor: colors.darkBorder},
  header: {paddingHorizontal: 20, paddingTop: 20, paddingBottom: 14, flexDirection: 'row', alignItems: 'center'},
  headerCopy: {flex: 1},
  eyebrow: {fontSize: 10, letterSpacing: 2, color: colors.accent, fontWeight: '900'},
  title: {fontSize: 34, lineHeight: 40, color: colors.ink, fontFamily: 'serif', fontWeight: '700'},
  subtitle: {fontSize: 12, color: colors.muted, marginTop: 2},
  clearButton: {height: 38, paddingHorizontal: 14, borderRadius: 13, backgroundColor: colors.ink, borderWidth: 1, borderColor: colors.ink, alignItems: 'center', justifyContent: 'center'},
  clearButtonDark: {backgroundColor: colors.darkSurface, borderColor: colors.focus},
  clearButtonText: {fontSize: 12, fontWeight: '900', color: colors.focus},
  disabled: {opacity: 0.35},
  searchBox: {height: 46, marginHorizontal: 20, marginBottom: 16, paddingHorizontal: 14, borderRadius: 15, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.border},
  searchBoxDark: {backgroundColor: colors.darkSurface, borderColor: colors.darkBorder},
  searchGlyph: {fontFamily: 'serif', fontSize: 13, color: colors.accentDark, fontWeight: '800', marginRight: 10},
  searchInput: {flex: 1, color: colors.ink, fontSize: 14, paddingVertical: 0},
  searchClear: {fontSize: 22, lineHeight: 24, color: colors.muted, paddingLeft: 10},
  centered: {flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 36},
  emptyGlyph: {width: 70, height: 70, borderRadius: 22, backgroundColor: colors.ink, borderWidth: 2, borderColor: colors.focus, alignItems: 'center', justifyContent: 'center', marginBottom: 20},
  emptyGlyphText: {fontFamily: 'serif', fontSize: 25, color: colors.focus, fontWeight: '700'},
  emptyTitle: {fontFamily: 'serif', fontSize: 22, fontWeight: '700', color: colors.ink, textAlign: 'center'},
  emptyCopy: {fontSize: 14, lineHeight: 22, color: colors.muted, textAlign: 'center', marginTop: 10, maxWidth: 330},
  list: {paddingHorizontal: 20, paddingBottom: 112},
  card: {backgroundColor: colors.paper, borderRadius: 17, borderWidth: 1, borderColor: colors.border, padding: 16, marginBottom: 11},
  cardHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  cardWord: {fontSize: 21, fontFamily: 'serif', fontWeight: '700', color: colors.ink},
  cardPos: {backgroundColor: colors.focus, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, color: colors.ink, fontSize: 9, fontWeight: '900', overflow: 'hidden'},
  cardPosMuted: {fontSize: 14, color: colors.muted},
  cardNotFound: {marginTop: 8, fontSize: 13, color: colors.muted},
  previewRow: {flexDirection: 'row', alignItems: 'center'},
  cardPreview: {flex: 1, marginTop: 8, fontSize: 13, lineHeight: 19, color: colors.muted},
  expandArrow: {fontSize: 25, color: colors.accentDark, marginLeft: 10},
  cardDetail: {marginTop: 13, paddingTop: 11, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border},
  entry: {marginBottom: 11},
  entryPos: {fontSize: 9, letterSpacing: 1.2, color: colors.accentDark, fontWeight: '800', marginBottom: 5},
  definition: {fontSize: 14, lineHeight: 21, color: colors.ink},
  example: {marginTop: 7, fontSize: 13, lineHeight: 19, color: colors.muted, fontStyle: 'italic'},
  collapseHint: {fontSize: 10, color: colors.accentDark, fontWeight: '700', textAlign: 'right'},
  attribution: {fontSize: 10, color: colors.muted, textAlign: 'center', marginTop: 8},
});

export default styles;
