import {StyleSheet} from 'react-native';
import {colors} from '../constants/theme';

const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: colors.background},
  safeAreaDark: {backgroundColor: colors.darkBackground},
  header: {paddingHorizontal: 20, paddingTop: 20, paddingBottom: 12},
  eyebrow: {fontSize: 10, letterSpacing: 2, color: colors.accent, fontWeight: '900'},
  title: {fontFamily: 'serif', fontSize: 40, lineHeight: 46, color: colors.ink, fontWeight: '700'},
  subtitle: {fontSize: 12, color: colors.muted, marginTop: 2},
  content: {paddingHorizontal: 20, paddingBottom: 112},
  sectionLabel: {fontSize: 11, letterSpacing: 1.7, color: colors.muted, fontWeight: '800', marginTop: 16, marginBottom: 8},
  card: {backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 16, shadowColor: colors.shadow, shadowOpacity: 0.05, shadowRadius: 12, shadowOffset: {width: 0, height: 6}, elevation: 2},
  cardDark: {backgroundColor: colors.darkSurface, borderColor: colors.darkBorder},
  cardTitle: {fontSize: 16, color: colors.ink, fontWeight: '800'},
  cardCopy: {fontSize: 13, lineHeight: 19, color: colors.muted, marginTop: 4},
  textDark: {color: colors.darkInk},
  mutedDark: {color: colors.darkMuted},
  rowBetween: {flexDirection: 'row', alignItems: 'center'},
  toggleRow: {flexDirection: 'row', alignItems: 'center'},
  flex: {flex: 1},
  statusDot: {width: 11, height: 11, borderRadius: 6, backgroundColor: '#A59D94', marginLeft: 12},
  statusDotReady: {backgroundColor: '#4F9365'},
  primaryButton: {height: 46, borderRadius: 15, overflow: 'hidden', marginTop: 16, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center'},
  primaryButtonText: {fontSize: 14, color: colors.focus, fontWeight: '900'},
  primaryButtonDark: {backgroundColor: 'transparent'},
  primaryButtonTextDark: {color: colors.ink},
  busyButtonContent: {flexDirection: 'row', alignItems: 'center', gap: 9},
  modelProgressTrack: {height: 6, marginTop: 10, borderRadius: 3, overflow: 'hidden', backgroundColor: colors.border},
  modelProgressTrackDark: {backgroundColor: colors.darkBorder},
  modelProgressFill: {height: 6, borderRadius: 3, backgroundColor: colors.focus},
  downloadNote: {fontSize: 11, lineHeight: 16, color: colors.muted, textAlign: 'center', marginTop: 9},
  disabled: {opacity: 0.55},
  voiceSelect: {minHeight: 58, flexDirection: 'row', alignItems: 'center', borderRadius: 13, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, paddingVertical: 9},
  voiceSelectDark: {backgroundColor: colors.darkSurfaceRaised, borderColor: colors.darkBorder},
  voiceSelectOpen: {borderColor: colors.focus},
  voiceName: {fontSize: 14, color: colors.ink, fontWeight: '800'},
  voiceCode: {fontSize: 11, color: colors.muted, marginTop: 2},
  voiceChevron: {fontSize: 11, color: colors.ink, marginLeft: 12},
  voiceMenu: {maxHeight: 282, marginTop: 8, borderRadius: 13, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.background},
  voiceMenuDark: {backgroundColor: colors.darkSurfaceRaised, borderColor: colors.darkBorder},
  voiceOption: {minHeight: 54, flexDirection: 'row', alignItems: 'center', overflow: 'hidden', paddingHorizontal: 14, paddingVertical: 8},
  voiceOptionDark: {backgroundColor: colors.darkSurfaceRaised},
  voiceOptionBorder: {borderBottomWidth: 1, borderBottomColor: colors.border},
  voiceOptionBorderDark: {borderBottomColor: colors.darkBorder},
  voiceOptionSelected: {backgroundColor: 'transparent'},
  voiceCheck: {fontSize: 18, color: colors.ink, fontWeight: '900', marginLeft: 12},
  choiceDark: {backgroundColor: colors.darkSurfaceRaised, borderColor: colors.darkBorder},
  choiceActive: {backgroundColor: 'transparent', borderColor: colors.ink},
  choiceTextActive: {color: colors.ink},
  speedRow: {flexDirection: 'row', gap: 7},
  speedChoice: {flex: 1, height: 40, borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center'},
  speedText: {fontSize: 12, color: colors.ink, fontWeight: '700'},
  helpButton: {minHeight: 76, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.border, borderRadius: 18, paddingHorizontal: 16, paddingVertical: 14},
  helpButtonDark: {backgroundColor: colors.darkSurface, borderColor: colors.darkBorder},
  helpButtonPressed: {opacity: 0.72},
  helpArrow: {fontSize: 28, lineHeight: 30, color: colors.accent, marginLeft: 14},
});

export default styles;
